"""empty message

Revision ID: 514a913e972e
Revises: 1dd07dbe901e
Create Date: 2022-03-09 15:27:04.634260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514a913e972e'
down_revision = '1dd07dbe901e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microscopes', sa.Column('vendor', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('microscopes', 'vendor')
    # ### end Alembic commands ###
