"""empty message

Revision ID: f8555058e65f
Revises: 87c096b1cbbc
Create Date: 2022-05-12 14:59:23.218418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8555058e65f'
down_revision = '87c096b1cbbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('microscope_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('hist_x', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('hist_y', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('roi_data', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('cv_table_sd', sa.Float(), nullable=False),
    sa.Column('cv_table_average', sa.Float(), nullable=False),
    sa.Column('cv_table_nb_pixels', sa.Float(), nullable=False),
    sa.Column('cv_table_cv_value', sa.Float(), nullable=False),
    sa.Column('cv_table_relative_to_min', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['microscope_id'], ['microscopes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homogeneities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('microscope_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('max_region_table_nb_pixels', sa.Integer(), nullable=False),
    sa.Column('max_region_table_center_of_mass', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('max_region_table_max_intensity', sa.Integer(), nullable=False),
    sa.Column('intensity_plot_data_x_axis_V_seg', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('intensity_plot_data_y_axis_V_seg', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('intensity_plot_data_x_axis_H_seg', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('intensity_plot_data_y_axis_H_seg', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('intensity_plot_data_x_axis_diagUD', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('intensity_plot_data_y_axis_diagUD', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('intensity_plot_data_x_axis_diagDU', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('intensity_plot_data_y_axis_diagDU', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('profile_stat_table_location', sa.String(length=128), nullable=False),
    sa.Column('profile_stat_table_intensity', sa.Float(), nullable=False),
    sa.Column('profile_stat_table_intensity_relative_to_max', sa.Float(), nullable=False),
    sa.Column('norm_intensity_data', sa.ARRAY(sa.Float(), dimensions=2), nullable=True),
    sa.ForeignKeyConstraint(['microscope_id'], ['microscopes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homogeneities')
    op.drop_table('cv')
    # ### end Alembic commands ###
